rate-limits.status.max-count=2
rate-limits.status.window=PT1M  # 1 minute ISO-8601

rate-limits.news.max-count=1
rate-limits.news.window=P1D     # 1 day

rate-limits.marketing.max-count=3
rate-limits.marketing.window=PT1H   # 1 hour